config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users
  resources :items
end

app/models/item.rb
class Item < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      flash[:notice] = 'Successfully Added'
      redirect_to items_path
    else
      flash[:notice] = @item.errrors.full_messages.join('. ')
      render items_path
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:notice] = 'Successfully Updated'
      redirect_to items_path
    else
      flash[:notice] = @item.errrors.full_messages.join('. ')
      render :edit
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:notice] = 'Successfully Deleted'
    redirect_to items_path
  end

  private

  def item_params
    params.required(:item).permit(:name, :price)
  end
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/items/_new.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
  </tr>
  <%= form_for @item, remote: true do |f| %>
    <tr>
      <td><%= f.text_field :name %></td>
      <td><%= f.text_field :price %></td>
      <td><%= f.submit 'Submit', class: "button round" %></td>
    </tr>
  <%- end -%>
</table>

app/views/items/_show.html.erb
<table>
  <tr>
    <th>Partial View</th>
    <th>Name</th>
    <th>Price</th>
  </tr>
  <tr>
    <td></td>
    <td><%= @item.name %></td>
    <td><%= @item.price %></td>
  </tr>
</table>

app/views/items/edit.html.erb
<h2>this is the edit page for items</h2>

<p><%= link_to 'Back to items', items_path %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
  </tr>
  <%= form_for @item do |f| %>
    <tr>
      <td><%= f.text_field :name %></td>
      <td><%= f.text_field :price %></td>
      <td><%= f.submit 'Submit', class: "button round" %></td>
    </tr>
  <%- end -%>
</table>

app/views/items/index.html.erb
<h2>this is the index page for items</h2>

<p><%= link_to 'Add new item', new_item_path, id: 'new-link', remote: true %></p>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th>Price</th>
    <th>Date Added</th>
  </tr>

  <% @items.each do |item| %>
  <tr class='item'>
    <td><%= link_to "#{item.name}", item_path(item), id: "show" %></td>
    <td class='reveal'><button>Show Price</button>
    <td><span class='price'><%= item.price %></span></td>
    <td><%= item.created_at.strftime('%m/%d/%y') %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Delete', item_path(item), method: :delete %></td>
  </tr>
  <tr>
    <% render 'show', :@item => item %>
  </tr>
  <%- end -%>
</table>

app/views/items/new.html.erb
<h2>this is the new page for items</h2>

<p><%= link_to 'Back to items', items_path %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
  </tr>
  <%= form_for @item do |f| %>
    <tr>
      <td><%= f.text_field :name %></td>
      <td><%= f.text_field :price %></td>
      <td><%= f.submit 'Submit', class: "button round" %></td>
    </tr>
  <%- end -%>
</table>

app/views/items/new.js.erb
$('#new-link').hide().after('<%= j render("new") %>');

app/views/items/show.html.erb
<h2>show page</h2>

<p><%= link_to 'Back to Items', items_path %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
  </tr>
  <tr>
    <td><%= @item.name %></td>
    <td><%= @item.price %></td>
  </tr>
</table>

app/views/items/show.js.erb
$("#show").click(<%= j render('show') %>);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buylist</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Buylist</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><% link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><% link_to 'Sign Up', new_user_registration_path %></li>
          <li><% link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>